In [ ]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [2]:
import torch
import numpy as np

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [6]:
type(x_data)

torch.Tensor

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
np_array

array([[1, 2],
       [3, 4]])

In [9]:
x_np

tensor([[1, 2],
        [3, 4]])

In [10]:
# prompt: convert the tensor x_np to a numpy arrary named y

y = x_np.numpy()
y


array([[1, 2],
       [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [11]:
x_ones = torch.ones_like(x_data) # retains the shape of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3270, 0.7995],
        [0.8617, 0.6643]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [15]:
shape2 = (2,3)
ones_tensor2 = torch.ones(shape2)

ones_tensor == ones_tensor2


tensor([[True, True, True],
        [True, True, True]])

In [14]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2383, 0.4738, 0.8697],
        [0.6505, 0.7406, 0.4496]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [4]:
tensor = torch.rand(3, 4)
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.8644, 0.9523, 0.8779, 0.3890],
        [0.0695, 0.1238, 0.7474, 0.3119],
        [0.5727, 0.9427, 0.2068, 0.3838]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
torch.ones(3,4) == torch.ones((3,4))

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [19]:
torch.ones(2,2, 2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [5]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [6]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
tensor[1,:] = -1
print(tensor)

tensor([[ 1.,  0.,  1.,  1.],
        [-1., -1., -1., -1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.]])


In [9]:
t0 = torch.cat([tensor, tensor, tensor], dim=0)
print(t0)

tensor([[ 1.,  0.,  1.,  1.],
        [-1., -1., -1., -1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [-1., -1., -1., -1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [-1., -1., -1., -1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.]])


In [13]:
tensor.dim(), tensor.shape

(2, torch.Size([4, 4]))

**Multiplying tensors**


In [14]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


This computes the matrix multiplication between two tensors


In [15]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[ 3., -3.,  3.,  3.],
        [-3.,  4., -3., -3.],
        [ 3., -3.,  3.,  3.],
        [ 3., -3.,  3.,  3.]]) 

tensor @ tensor.T 
 tensor([[ 3., -3.,  3.,  3.],
        [-3.,  4., -3., -3.],
        [ 3., -3.,  3.,  3.],
        [ 3., -3.,  3.,  3.]])


In [16]:
tensor.T @ tensor

tensor([[4., 1., 4., 4.],
        [1., 1., 1., 1.],
        [4., 1., 4., 4.],
        [4., 1., 4., 4.]])

**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [17]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[ 1.,  0.,  1.,  1.],
        [-1., -1., -1., -1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.]]) 

tensor([[6., 5., 6., 6.],
        [4., 4., 4., 4.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [20]:
print(tensor.t_())

tensor([[6., 4., 6., 6.],
        [5., 4., 5., 5.],
        [6., 4., 6., 6.],
        [6., 4., 6., 6.]])


In [26]:
tc = tensor.copy_(tensor)
print(tc)
tc.add_(-5)
print(tensor), print(tc)

tensor([[ 1., -1.,  1.,  1.],
        [ 0., -1.,  0.,  0.],
        [ 1., -1.,  1.,  1.],
        [ 1., -1.,  1.,  1.]])
tensor([[-4., -5., -4., -4.],
        [-6., -6., -6., -6.],
        [-4., -5., -4., -4.],
        [-4., -5., -4., -4.]])
tensor([[-4., -5., -4., -4.],
        [-6., -6., -6., -6.],
        [-4., -5., -4., -4.],
        [-4., -5., -4., -4.]])


(None, None)

In [29]:
# prompt: how to create a deep copy of a tensor

import torch

# Assuming 'tensor' is the tensor you want to copy
tensor_copy = tensor.clone()

# Now tensor_copy is a completely independent copy of 'tensor'
# Any modifications to tensor_copy will not affect the original 'tensor'


In [32]:
print(tensor)
print(tensor_copy)
tensor_copy.add_(-5)
print(tensor), print(tensor_copy)

tensor([[ -9., -10.,  -9.,  -9.],
        [-11., -11., -11., -11.],
        [ -9., -10.,  -9.,  -9.],
        [ -9., -10.,  -9.,  -9.]])
tensor([[-19., -20., -19., -19.],
        [-21., -21., -21., -21.],
        [-19., -20., -19., -19.],
        [-19., -20., -19., -19.]])
tensor([[ -9., -10.,  -9.,  -9.],
        [-11., -11., -11., -11.],
        [ -9., -10.,  -9.,  -9.],
        [ -9., -10.,  -9.,  -9.]])
tensor([[-24., -25., -24., -24.],
        [-26., -26., -26., -26.],
        [-24., -25., -24., -24.],
        [-24., -25., -24., -24.]])


(None, None)

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [33]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [34]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [37]:
n = np.ones(5)
t = torch.from_numpy(n)
print(n), print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


(None, None)

Changes in the NumPy array reflects in the tensor.


In [38]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
